### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brandoncurtis** [mattjj/py4sid#1]
Can you briefly summarize what `test.py` is doing?

I'm familiar with state space representation of dynamical systems, but I'm getting tripped up because the ABCD matrices don't have the dimensions I think they should have.

n = # of states
m = # of inputs
p = # of outputs

A: [n x n]
B: [n x m]
C: [p x n]
D: [p x m]

But in `rand_lds()`:

```python
A = np.real(T.dot(np.diag(eigvals)).dot(np.linalg.inv(T)))  # [n x n] as expected
B = np.eye(n)                 # [n x n], but I would think it should be [n x m]
C = randn(p,n)               # [p x n] as expected
D = 0.1*np.eye(p)          # [p x p], but I would think it should be [p x m]
```

Can you help clarify?

**Comment by mattjj** [comment]
`B` and `D` are [square roots of `Q` and `R`](https://github.com/mattjj/py4sid/blob/5c1b5ea0a793254fe72b4b16ac6dbb0129446f72/estimation.py#L66-L67). That is, the variable naming conventions follow this model with no control inputs

```
x_{t+1} = A x_t + B u_t,  u_t ~ N(0, I) (iid)
y_t = C x_t + D v_t,  v_t ~ N(0, I) (iid)
```

This notational convention isn't standard in control, but it's one I got used to when modeling systems without control inputs, and which this code inherited because I was intending to use it to initialize EM learning in systems without controls. It would be good to revise it, though, and follow a more standard convention like

```
x_{t+1} = A x_t + B u_t + w_t,  w_t ~ N(0, Q) (iid)
y_t = C x_t + D u_t + v_t,  v_t ~ N(0, R) (iid)
```

**Comment by mattjj** [comment]
I'm not working on this code right now, so pull requests for code and/or documentation are welcome!

**Comment by brandoncurtis** [comment]
Thanks Matt!  In the short-term I'm checking out https://github.com/AndyLamperski/pyN4SID to see if that'll do what I need.  There appear to be a lot of tools in Python for manipulating state space models, but not a lot out there for building them from data in the first place.
